---
title: "DataSynthesis"
author: "glc5pn"
date: "3/22/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tm)
library(topicmodels)
library(SnowballC)
library(ggwordcloud)
library(RColorBrewer)
library(syuzhet)
library(lexicon)
library(tidytext)
library(textdata)
library(xgboost)
library(parallel)
library(caret)
library(stringr)
library(MASS)

setwd("~/School/4th Year/DS4002/Github/DS4002_Proj2")
#setwd("jonathan's File Path")
```


```{r read-in, include = FALSE}
teamResults.08 = read.csv("Team Results Stats/2008_team_results.csv", header = FALSE)[-c(1),]
names(teamResults.08) = read.csv("Team Results Stats/2008_team_results.csv", header = FALSE)[1,]
teamResults.09 = read.csv("Team Results Stats/2009_team_results.csv", header = FALSE)[-c(1),]
names(teamResults.09) = read.csv("Team Results Stats/2009_team_results.csv", header = FALSE)[1,]
teamResults.10 = read.csv("Team Results Stats/2010_team_results.csv", header = FALSE)[-c(1),]
names(teamResults.10) = read.csv("Team Results Stats/2010_team_results.csv", header = FALSE)[1,]
teamResults.11 = read.csv("Team Results Stats/2011_team_results.csv", header = FALSE)[-c(1),]
names(teamResults.11) = read.csv("Team Results Stats/2011_team_results.csv", header = FALSE)[1,]
teamResults.12 = read.csv("Team Results Stats/2012_team_results.csv", header = FALSE)[-c(1),]
names(teamResults.12) = read.csv("Team Results Stats/2012_team_results.csv", header = FALSE)[1,]
teamResults.13 = read.csv("Team Results Stats/2013_team_results.csv", header = FALSE)[-c(1),]
names(teamResults.13) = read.csv("Team Results Stats/2013_team_results.csv", header = FALSE)[1,]
teamResults.14 = read.csv("Team Results Stats/2014_team_results.csv", header = FALSE)[-c(1),]
names(teamResults.14) = read.csv("Team Results Stats/2014_team_results.csv", header = FALSE)[1,]
teamResults.15 = read.csv("Team Results Stats/2015_team_results.csv", header = FALSE)[-c(1),]
names(teamResults.15) = read.csv("Team Results Stats/2015_team_results.csv", header = FALSE)[1,]
teamResults.16 = read.csv("Team Results Stats/2016_team_results.csv", header = FALSE)[-c(1),]
names(teamResults.16) = read.csv("Team Results Stats/2016_team_results.csv", header = FALSE)[1,]
teamResults.17 = read.csv("Team Results Stats/2017_team_results.csv", header = FALSE)[-c(1),]
names(teamResults.17) = read.csv("Team Results Stats/2017_team_results.csv", header = FALSE)[1,]
teamResults.18 = read.csv("Team Results Stats/2018_team_results.csv", header = FALSE)[-c(1),]
names(teamResults.18) = read.csv("Team Results Stats/2018_team_results.csv", header = FALSE)[1,]
teamResults.19 = read.csv("Team Results Stats/2019_team_results.csv", header = FALSE)[-c(1),]
names(teamResults.19) = read.csv("Team Results Stats/2019_team_results.csv", header = FALSE)[1,]
teamResults.20 = read.csv("Team Results Stats/2020_team_results.csv", header = FALSE)[-c(1),]
names(teamResults.20) = read.csv("Team Results Stats/2020_team_results.csv", header = FALSE)[1,]
teamResults.21 = read.csv("Team Results Stats/2021_team_results.csv", header = FALSE)[-c(1),]
names(teamResults.21) = read.csv("Team Results Stats/2021_team_results.csv", header = FALSE)[1,]
teamResults.22 = read.csv("Team Results Stats/2022_team_results.csv", header = FALSE)[-c(1),]
names(teamResults.22) = read.csv("Team Results Stats/2022_team_results.csv", header = FALSE)[1,]


addYear = function(teamData) {
  year = substr(deparse(substitute(teamData)),nchar(deparse(substitute(teamData)))-1,nchar(deparse(substitute(teamData))))
  teamData$team = paste(year,teamData$team,sep = '.')
  return(teamData)
}

teamResults.08 = addYear(teamResults.08)
teamResults.09 = addYear(teamResults.09)
teamResults.10 = addYear(teamResults.10)
teamResults.11 = addYear(teamResults.11)
teamResults.12 = addYear(teamResults.12)
teamResults.13 = addYear(teamResults.13)
teamResults.14 = addYear(teamResults.14)
teamResults.15 = addYear(teamResults.15)
teamResults.16 = addYear(teamResults.16)
teamResults.17 = addYear(teamResults.17)
teamResults.18 = addYear(teamResults.18)
teamResults.19 = addYear(teamResults.19)
teamResults.20 = addYear(teamResults.20)
teamResults.21 = addYear(teamResults.21)
teamResults.22 = addYear(teamResults.22)


teamResultsAll = rbind(teamResults.08,teamResults.09,teamResults.10,teamResults.11,teamResults.12,teamResults.13,teamResults.14,teamResults.15,teamResults.16,teamResults.17,teamResults.18,teamResults.19,teamResults.20,teamResults.21,teamResults.22)



teamResultsAll = teamResultsAll[,-c(10)]
winRate = c()

for (i in 1:nrow(teamResultsAll)) {
  winRate.i = as.numeric(strsplit(teamResultsAll$record, "-")[[i]][1]) / (as.numeric(strsplit(teamResultsAll$record, "-")[[i]][2]) + as.numeric(strsplit(teamResultsAll$record, "-")[[i]][1]))
  winRate = c(winRate, winRate.i)
}

teamResultsAll = teamResultsAll %>% mutate("winRate" = winRate)

write.csv(teamResultsAll, "teamResultsData.csv")
```




```{r team stats}
teamStats.08 = read.csv("Team Overall Stats/2008_fffinal.csv", header = FALSE)[-c(1),]
names(teamStats.08) = read.csv("Team Overall Stats/2008_fffinal.csv", header = FALSE)[1,]
teamStats.09 = read.csv("Team Overall Stats/2009_fffinal.csv", header = FALSE)[-c(1),]
names(teamStats.09) = read.csv("Team Overall Stats/2009_fffinal.csv", header = FALSE)[1,]
teamStats.10 = read.csv("Team Overall Stats/2010_fffinal.csv", header = FALSE)[-c(1),]
names(teamStats.10) = read.csv("Team Overall Stats/2010_fffinal.csv", header = FALSE)[1,]
teamStats.11 = read.csv("Team Overall Stats/2011_fffinal.csv", header = FALSE)[-c(1),]
names(teamStats.11) = read.csv("Team Overall Stats/2011_fffinal.csv", header = FALSE)[1,]
teamStats.12 = read.csv("Team Overall Stats/2012_fffinal.csv", header = FALSE)[-c(1),]
names(teamStats.12) = read.csv("Team Overall Stats/2012_fffinal.csv", header = FALSE)[1,]
teamStats.13 = read.csv("Team Overall Stats/2013_fffinal.csv", header = FALSE)[-c(1),]
names(teamStats.13) = read.csv("Team Overall Stats/2013_fffinal.csv", header = FALSE)[1,]
teamStats.14 = read.csv("Team Overall Stats/2014_fffinal.csv", header = FALSE)[-c(1),]
names(teamStats.14) = read.csv("Team Overall Stats/2014_fffinal.csv", header = FALSE)[1,]
teamStats.15 = read.csv("Team Overall Stats/2015_fffinal.csv", header = FALSE)[-c(1),]
names(teamStats.15) = read.csv("Team Overall Stats/2015_fffinal.csv", header = FALSE)[1,]
teamStats.16 = read.csv("Team Overall Stats/2016_fffinal.csv", header = FALSE)[-c(1),]
names(teamStats.16) = read.csv("Team Overall Stats/2016_fffinal.csv", header = FALSE)[1,]
teamStats.17 = read.csv("Team Overall Stats/2017_fffinal.csv", header = FALSE)[-c(1),]
names(teamStats.17) = read.csv("Team Overall Stats/2017_fffinal.csv", header = FALSE)[1,]
teamStats.18 = read.csv("Team Overall Stats/2018_fffinal.csv", header = FALSE)[-c(1),]
names(teamStats.18) = read.csv("Team Overall Stats/2018_fffinal.csv", header = FALSE)[1,]
teamStats.19 = read.csv("Team Overall Stats/2019_fffinal.csv", header = FALSE)[-c(1),]
names(teamStats.19) = read.csv("Team Overall Stats/2019_fffinal.csv", header = FALSE)[1,]
teamStats.20 = read.csv("Team Overall Stats/2020_fffinal.csv", header = FALSE)[-c(1),]
names(teamStats.20) = read.csv("Team Overall Stats/2020_fffinal.csv", header = FALSE)[1,]
teamStats.21 = read.csv("Team Overall Stats/2021_fffinal.csv", header = FALSE)[-c(1),]
names(teamStats.21) = read.csv("Team Overall Stats/2021_fffinal.csv", header = FALSE)[1,]
teamStats.22 = read.csv("Team Overall Stats/2022_fffinal.csv", header = FALSE)[-c(1),]
names(teamStats.22) = read.csv("Team Overall Stats/2022_fffinal.csv", header = FALSE)[1,]


addStatsYear = function(teamData) {
  year = substr(deparse(substitute(teamData)),nchar(deparse(substitute(teamData)))-1,nchar(deparse(substitute(teamData))))
  teamData$TeamName = paste(year,teamData$TeamName,sep = '.')
  return(teamData)
}


teamStats.08 = addStatsYear(teamStats.08)
teamStats.09 = addStatsYear(teamStats.09)
teamStats.10 = addStatsYear(teamStats.10)
teamStats.11 = addStatsYear(teamStats.11)
teamStats.12 = addStatsYear(teamStats.12)
teamStats.13 = addStatsYear(teamStats.13)
teamStats.14 = addStatsYear(teamStats.14)
teamStats.15 = addStatsYear(teamStats.15)
teamStats.16 = addStatsYear(teamStats.16)
teamStats.17 = addStatsYear(teamStats.17)
teamStats.18 = addStatsYear(teamStats.18)
teamStats.19 = addStatsYear(teamStats.19)
teamStats.20 = addStatsYear(teamStats.20)
teamStats.21 = addStatsYear(teamStats.21)
teamStats.22 = addStatsYear(teamStats.22)



teamStatsAll = rbind(teamStats.08,teamStats.09,teamStats.10,teamStats.11,teamStats.12,teamStats.13,teamStats.14,teamStats.15,teamStats.16,teamStats.17,teamStats.18,teamStats.19,teamStats.20,teamStats.21,teamStats.22)

teamStatsAll = teamStatsAll[,1:37]


write.csv(teamStatsAll, "teamStatsData.csv")
```


```{r Combine Game Data}
games.09 = read.csv("Team Game stats/2009_super_sked.csv", header = TRUE)
games.10 = read.csv("Team Game stats/2010_super_sked.csv", header = FALSE)[,-c(21:22,51:55)]
names(games.10) = names(games.09)
games.11 = read.csv("Team Game stats/2011_super_sked.csv", header = FALSE)[,-c(21:22,51:55)]
names(games.11) = names(games.09)
games.12 = read.csv("Team Game stats/2012_super_sked.csv", header = FALSE)[,-c(21:22,51:55)]
names(games.12) = names(games.09)
games.13 = read.csv("Team Game stats/2013_super_sked.csv", header = FALSE)[,-c(21:22,51:55)]
names(games.13) = names(games.09)
games.14 = read.csv("Team Game stats/2014_super_sked.csv", header = FALSE)[,-c(21:22,51:55)]
names(games.14) = names(games.09)
games.15 = read.csv("Team Game stats/2015_super_sked.csv", header = FALSE)[,-c(21:22,51:55)]
names(games.15) = names(games.09)
games.16 = read.csv("Team Game stats/2016_super_sked.csv", header = FALSE)[,-c(21:22,51:55)]
names(games.16) = names(games.09)
games.17 = read.csv("Team Game stats/2017_super_sked.csv", header = FALSE)[,-c(21:22,51:55)]
names(games.17) = names(games.09)
games.18 = read.csv("Team Game stats/2018_super_sked.csv", header = FALSE)[,-c(21:22,51:55)]
names(games.18) = names(games.09)
games.19 = read.csv("Team Game stats/2019_super_sked.csv", header = FALSE)[,-c(21:22,51:55)]
names(games.19) = names(games.09)
games.20 = read.csv("Team Game stats/2020_super_sked.csv", header = FALSE)[,-c(21:22,51:55)]
names(games.20) = names(games.09)
games.21 = read.csv("Team Game stats/2021_super_sked.csv", header = FALSE)[,-c(21:22,51:55)]
names(games.21) = names(games.09)
games.22 = read.csv("Team Game stats/2022_super_sked.csv", header = FALSE)[,-c(21:22,51:55)]
names(games.22) = names(games.09)

addYearGames = function(gameData) {
  year = substr(deparse(substitute(gameData)),nchar(deparse(substitute(gameData)))-1,nchar(deparse(substitute(gameData))))
  gameData$team1 = paste(year,gameData$team1,sep = '.')
  gameData$team2 = paste(year,gameData$team2,sep = '.')
  return(gameData)
}

games.09 = addYearGames(games.09)
games.10 = addYearGames(games.10)
games.11 = addYearGames(games.11)
games.12 = addYearGames(games.12)
games.13 = addYearGames(games.13)
games.14 = addYearGames(games.14)
games.15 = addYearGames(games.15)
games.16 = addYearGames(games.16)
games.17 = addYearGames(games.17)
games.18 = addYearGames(games.18)
games.19 = addYearGames(games.19)
games.20 = addYearGames(games.20)
games.21 = addYearGames(games.21)
games.22 = addYearGames(games.22)


gamesAll = rbind(games.09,games.10,games.11,games.12,games.13,games.14,games.15,games.16,games.17,games.18,games.19,games.20,games.21,games.22)


write.csv(gamesAll, "gamesData.csv")
```



```{r gameCleaning}

matchTeam()

```



